name: sportbudies
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  animations: ^2.0.4
  flutter_svg: any
  feather_icons_svg: any
  flutter_feather_icons: ^2.0.0+1
  intl_phone_field: ^3.1.0
  google_fonts: ^3.0.1
  provider: ^6.0.3
  intl: ^0.17.0
  uuid: 3.0.6
  styled_widget: ^0.4.0+3
  crypto: ^3.0.2
  pinput: ^2.2.23
  cloud_firestore: ^4.0.4
  firebase_auth: ^4.1.1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  json_serializable: ^6.3.1

  modal_bottom_sheet: #^2.1.2
    git:
      url: https://github.com/duythien0912/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  image_picker: ^0.8.5+3
  image_crop: ^0.4.1
  webview_flutter: ^2.0.8
  shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  build_runner: ^2.1.11

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/icons/
  #   - images/a_dot_ham.jpeg

